Update terraform-drift-agent.yml

diff --git a/.github/workflows/terraform-drift-agent.yml b/.github/workflows/terraform-drift-agent.yml
--- a/.github/workflows/terraform-drift-agent.yml
+++ b/.github/workflows/terraform-drift-agent.yml
@@ -1,27 +1,29 @@
 name: Terraform Drift Detection Agent
 
+
 on:
 
+  pull_request:
+    branches:
+      - main
+
   workflow_dispatch:
-    inputs:
-      environment:
-        description: "Environment to check"
-        required: true
-        default: dev
 
   schedule:
     - cron: "0 2 * * *"
 
 
+
 permissions:
+
   id-token: write
   contents: write
   pull-requests: write
+  models: read
+
 
 
 env:
-
-  TF_VERSION: "1.8.5"
 
   TF_WORKING_DIR: ./environments/dev
 
@@ -29,26 +31,37 @@ env:
 
 jobs:
 
-# --------------------------------------------------
-# Detect Terraform Drift
-# --------------------------------------------------
 
-  drift-check:
+  drift:
+
 
     name: Terraform Drift Detection
 
+
     runs-on: ubuntu-latest
+
 
 
     steps:
 
 
-    - name: Checkout repository
+
+    ##########################################################
+    # Checkout
+    ##########################################################
+
+    - name: Checkout Repository
+
       uses: actions/checkout@v4
 
 
 
-    - name: Azure Login using OIDC
+    ##########################################################
+    # Azure Login (OIDC)
+    ##########################################################
+
+    - name: Azure Login
+
       uses: azure/login@v2
 
       with:
@@ -61,23 +74,38 @@ jobs:
 
 
 
+    ##########################################################
+    # Terraform Setup
+    ##########################################################
+
     - name: Setup Terraform
+
       uses: hashicorp/setup-terraform@v3
 
-      with:
-
-        terraform_version: ${{ env.TF_VERSION }}
 
 
+    - name: Terraform Version
+
+      run: terraform version
+
+
+
+    ##########################################################
+    # Terraform Init
+    ##########################################################
 
     - name: Terraform Init
+
       working-directory: ${{ env.TF_WORKING_DIR }}
 
-      run: |
-
-        terraform init
+      run: terraform init
 
 
+
+
+    ##########################################################
+    # Terraform Drift Detection
+    ##########################################################
 
     - name: Terraform Plan
 
@@ -87,17 +115,38 @@ jobs:
 
       continue-on-error: true
 
+
       run: |
 
         terraform plan \
-        -detailed-exitcode \
-        -out=tfplan
+          -out=tfplan \
+          -detailed-exitcode \
+          -input=false
+
+
+        EXIT_CODE=$?
+
+
+        echo "exitcode=$EXIT_CODE" >> $GITHUB_OUTPUT
 
 
 
-    - name: Convert Plan to JSON
+        if [ $EXIT_CODE -eq 1 ]; then
 
-      if: steps.plan.outcome == 'failure'
+          exit 1
+
+        fi
+
+
+
+
+    ##########################################################
+    # Export Terraform Plan JSON
+    ##########################################################
+
+    - name: Export Plan JSON
+
+      if: steps.plan.outputs.exitcode == '2'
 
       working-directory: ${{ env.TF_WORKING_DIR }}
 
@@ -105,9 +154,226 @@ jobs:
 
         terraform show \
         -json tfplan \
-        > plan.json
+        > tfplan.json
 
 
+
+
+    ##########################################################
+    # Export Current Terraform State
+    ##########################################################
+
+    - name: Export Terraform State
+
+      if: steps.plan.outputs.exitcode == '2'
+
+      working-directory: ${{ env.TF_WORKING_DIR }}
+
+      run: |
+
+        terraform state pull \
+        > terraform.tfstate.json
+
+
+
+
+    ##########################################################
+    # Python Setup
+    ##########################################################
+
+    - name: Setup Python
+
+      if: steps.plan.outputs.exitcode == '2'
+
+      uses: actions/setup-python@v5
+
+      with:
+
+        python-version: "3.12"
+
+
+
+    - name: Install Dependencies
+
+      if: steps.plan.outputs.exitcode == '2'
+
+      run: |
+
+        python -m pip install --upgrade pip
+
+        pip install -r scripts/requirements.txt
+
+
+
+
+    ##########################################################
+    # Reports Directory
+    ##########################################################
+
+    - name: Create Reports Directory
+
+      if: steps.plan.outputs.exitcode == '2'
+
+      run:
+
+        mkdir -p reports
+
+
+
+
+    ##########################################################
+    # Analyze Drift
+    ##########################################################
+
+    - name: Analyze Drift
+
+      if: steps.plan.outputs.exitcode == '2'
+
+      run:
+
+        python scripts/drift.py
+
+
+
+
+    ##########################################################
+    # Prepare Terraform Changes
+    ##########################################################
+
+    - name: Prepare Terraform Changes
+
+      if: steps.plan.outputs.exitcode == '2'
+
+      run:
+
+        python scripts/terraform_modifier.py
+
+
+
+
+    ##########################################################
+    # Azure Activity Logs
+    ##########################################################
+
+    - name: Find Who Changed Infrastructure
+
+      if: steps.plan.outputs.exitcode == '2'
+
+      run:
+
+        python scripts/activitylog.py
+
+
+
+
+    ##########################################################
+    # Terraform Module Resolver
+    ##########################################################
+
+    - name: Resolve Terraform Modules
+
+      if: steps.plan.outputs.exitcode == '2'
+
+      run:
+
+        python scripts/module_resolver.py
+
+
+
+
+    ##########################################################
+    # Terraform Parser
+    ##########################################################
+
+    - name: Parse Terraform Configuration
+
+      if: steps.plan.outputs.exitcode == '2'
+
+      run:
+
+        python scripts/terraform_parser.py
+
+
+
+
+    ##########################################################
+    # Generate Report
+    ##########################################################
+
+    - name: Generate Report
+
+      if: steps.plan.outputs.exitcode == '2'
+
+      run:
+
+        python scripts/report.py
+
+
+
+
+    ##########################################################
+    # AI Summary
+    ##########################################################
+
+    - name: AI Summary
+
+      if: steps.plan.outputs.exitcode == '2'
+
+      env:
+
+        MODELS_PAT: ${{ secrets.MODELS_PAT }}
+
+      run:
+
+        python scripts/ai.py
+
+
+
+
+    ##########################################################
+    # Create Drift Fix Pull Request
+    ##########################################################
+
+    - name: Create Drift Fix PR
+
+      if: steps.plan.outputs.exitcode == '2'
+
+      env:
+
+        GH_TOKEN: ${{ github.token }}
+
+
+      run:
+
+        python scripts/github_pr.py
+
+
+
+
+    ##########################################################
+    # Upload Reports
+    ##########################################################
+
+    - name: Upload Reports
+
+      if: always()
+
+      uses: actions/upload-artifact@v4
+
+
+      with:
+
+        name: terraform-drift-report
+
+        path: reports/
+
+
+
+
+
+    ##########################################################
+    # Upload Terraform Plan
+    ##########################################################
 
     - name: Upload Terraform Plan
 
@@ -115,54 +381,47 @@ jobs:
 
       uses: actions/upload-artifact@v4
 
+
       with:
 
-        name: terraform-drift-plan
+        name: terraform-plan-json
 
         path:
 
-          ${{ env.TF_WORKING_DIR }}/plan.json
+          ${{ env.TF_WORKING_DIR }}/tfplan.json
 
 
 
 
-# --------------------------------------------------
-# Drift Analysis
-# --------------------------------------------------
 
-    - name: Install Python dependencies
+    ##########################################################
+    # GitHub Summary
+    ##########################################################
 
-      run: |
-
-        pip install requests
-
-
-
-    - name: Run Drift Analyzer
-
-      if: steps.plan.outcome == 'failure'
+    - name: Publish Summary
 
       run: |
 
-        python scripts/drift.py \
-        ${{ env.TF_WORKING_DIR }}/plan.json
+
+        echo "## Terraform Drift Detection" >> $GITHUB_STEP_SUMMARY
+
+        echo "" >> $GITHUB_STEP_SUMMARY
 
 
+        if [ "${{ steps.plan.outputs.exitcode }}" == "2" ]; then
+
+          echo "⚠️ Drift detected" >> $GITHUB_STEP_SUMMARY
+
+          echo "Terraform remediation PR created." >> $GITHUB_STEP_SUMMARY
 
 
-# --------------------------------------------------
-# Create Pull Request
-# --------------------------------------------------
+        elif [ "${{ steps.plan.outputs.exitcode }}" == "0" ]; then
 
-    - name: Create Drift Fix PR
-
-      if: steps.plan.outcome == 'failure'
-
-      env:
-
-        GH_TOKEN: ${{ github.token }}
+          echo "✅ No drift detected" >> $GITHUB_STEP_SUMMARY
 
 
-      run: |
+        else
 
-        python scripts/github_pr.py
+          echo "❌ Terraform execution failed" >> $GITHUB_STEP_SUMMARY
+
+        fi
